# 配置图像定位资源位置
IMAGE_DIR: "src"
# 配置应用程序
TING_EN_APP_PATH: "C:\\Program Files (x86)\\ting_en\\ting_en.exe"
TING_EN_IMAGE_NAME: "ting_en.exe"
# 配置钉钉机器人
WEBHOOK: "https://oapi.dingtalk.com/robot/send?access_token=<YOUR_ACCESS_TOKEN>"
SECRET: "<YOUR_SECRET>"